platform: Any CPU

configuration: Release

before_build:
  - cd src
  - nuget restore
  - cd ..

test: off

after_build: 7z a mdcat.zip .\src\mdcat\bin\Release\mdcat.exe

artifacts:
  - path: mdcat.zip
    name: mdcat
